FOODS = [
    # ── أرز وحبوب ────────────────────────────────────────────────────────────
    {
        "name": "أرز أبيض (مطبوخ)",
        "category": "أرز وحبوب",
        "carbs_per_100g": 28.2,
        "serving_size_g": 150,
        "serving_name": "كوب واحد",
        "image_url": "https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?w=400&q=80",
        "notes": "من أكثر الأطعمة شيوعاً — راقب الكمية",
    },
    {
        "name": "أرز بني (مطبوخ)",
        "category": "أرز وحبوب",
        "carbs_per_100g": 23.0,
        "serving_size_g": 150,
        "serving_name": "كوب واحد",
        "image_url": "https://images.unsplash.com/photo-1601314167099-232775b3d6fd?w=400&q=80",
        "notes": "أفضل من الأبيض — يحتوي على ألياف أكثر",
    },
    {
        "name": "شعير (مطبوخ)",
        "category": "أرز وحبوب",
        "carbs_per_100g": 28.2,
        "serving_size_g": 150,
        "serving_name": "كوب واحد",
        "image_url": "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&q=80",
        "notes": "غني بالألياف — مفيد لمرضى السكري",
    },
    {
        "name": "شوفان (مطبوخ)",
        "category": "أرز وحبوب",
        "carbs_per_100g": 12.0,
        "serving_size_g": 240,
        "serving_name": "كوب واحد",
        "image_url": "https://images.unsplash.com/photo-1495214783159-3503fd1b572d?w=400&q=80",
        "notes": "الألياف القابلة للذوبان تساعد على تنظيم السكر",
    },
    {
        "name": "كينوا (مطبوخة)",
        "category": "أرز وحبوب",
        "carbs_per_100g": 21.3,
        "serving_size_g": 185,
        "serving_name": "كوب واحد",
        "image_url": "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&q=80",
        "notes": "بروتين عالٍ وكربوهيدرات معتدلة",
    },
    {
        "name": "معكرونة (مطبوخة)",
        "category": "أرز وحبوب",
        "carbs_per_100g": 25.0,
        "serving_size_g": 140,
        "serving_name": "كوب واحد",
        "image_url": "https://images.unsplash.com/photo-1608219992759-8d74ed8d76eb?w=400&q=80",
        "notes": "الطهي المتوسط يقلل امتصاص الكارب",
    },
    {
        "name": "برغل (مطبوخ)",
        "category": "أرز وحبوب",
        "carbs_per_100g": 18.6,
        "serving_size_g": 182,
        "serving_name": "كوب واحد",
        "image_url": "https://images.unsplash.com/photo-1604135945956-a30cc5dcacf2?w=400&q=80",
        "notes": "خيار جيد — ألياف عالية",
    },
    # ── خبز ومعجنات ──────────────────────────────────────────────────────────
    {
        "name": "خبز أبيض",
        "category": "خبز ومعجنات",
        "carbs_per_100g": 49.0,
        "serving_size_g": 28,
        "serving_name": "شريحة واحدة",
        "image_url": "https://images.unsplash.com/photo-1598373182133-52452f7691ef?w=400&q=80",
        "notes": "كربوهيدرات مرتفعة — قلل من تناوله",
    },
    {
        "name": "خبز القمح الكامل",
        "category": "خبز ومعجنات",
        "carbs_per_100g": 43.0,
        "serving_size_g": 28,
        "serving_name": "شريحة واحدة",
        "image_url": "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&q=80",
        "notes": "أفضل من الأبيض — ألياف أكثر",
    },
    {
        "name": "خبز الشعير",
        "category": "خبز ومعجنات",
        "carbs_per_100g": 40.0,
        "serving_size_g": 28,
        "serving_name": "شريحة واحدة",
        "image_url": "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&q=80",
        "notes": "خيار ممتاز لمرضى السكري",
    },
    {
        "name": "كرواسون",
        "category": "خبز ومعجنات",
        "carbs_per_100g": 46.0,
        "serving_size_g": 57,
        "serving_name": "واحدة متوسطة",
        "image_url": "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400&q=80",
        "notes": "دهون ونشويات عالية — أحياناً فقط",
    },
    {
        "name": "بيتزا (قطعة واحدة)",
        "category": "خبز ومعجنات",
        "carbs_per_100g": 33.0,
        "serving_size_g": 107,
        "serving_name": "شريحة واحدة",
        "image_url": "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80",
        "notes": "كربوهيدرات عالية — راقب العدد",
    },
    {
        "name": "خبز التوست المحمص",
        "category": "خبز ومعجنات",
        "carbs_per_100g": 49.0,
        "serving_size_g": 25,
        "serving_name": "شريحة واحدة",
        "image_url": "https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=400&q=80",
        "notes": "كمية الكارب متشابهة مع الخبز العادي",
    },
    # ── فواكه ─────────────────────────────────────────────────────────────────
    {
        "name": "تفاح",
        "category": "فواكه",
        "carbs_per_100g": 14.0,
        "serving_size_g": 182,
        "serving_name": "حبة متوسطة",
        "image_url": "https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=400&q=80",
        "notes": "تناوله مع القشرة للألياف",
    },
    {
        "name": "موز",
        "category": "فواكه",
        "carbs_per_100g": 23.0,
        "serving_size_g": 118,
        "serving_name": "حبة متوسطة",
        "image_url": "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400&q=80",
        "notes": "الأخضر يرفع السكر أبطأ من الأصفر الناضج",
    },
    {
        "name": "برتقال",
        "category": "فواكه",
        "carbs_per_100g": 12.0,
        "serving_size_g": 131,
        "serving_name": "حبة متوسطة",
        "image_url": "https://images.unsplash.com/photo-1547514701-42782101795e?w=400&q=80",
        "notes": "مصدر ممتاز لفيتامين C",
    },
    {
        "name": "عنب",
        "category": "فواكه",
        "carbs_per_100g": 18.0,
        "serving_size_g": 92,
        "serving_name": "نصف كوب",
        "image_url": "https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=400&q=80",
        "notes": "راقب الكمية — سكريات طبيعية",
    },
    {
        "name": "فراولة",
        "category": "فواكه",
        "carbs_per_100g": 8.0,
        "serving_size_g": 152,
        "serving_name": "كوب واحد",
        "image_url": "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400&q=80",
        "notes": "خيار رائع — كربوهيدرات منخفضة",
    },
    {
        "name": "بطيخ",
        "category": "فواكه",
        "carbs_per_100g": 7.6,
        "serving_size_g": 280,
        "serving_name": "كوبان مقطّعان",
        "image_url": "https://images.unsplash.com/photo-1589984662646-e7b2e4962f18?w=400&q=80",
        "notes": "كارب منخفض للحصة الواحدة",
    },
    {
        "name": "مانجو",
        "category": "فواكه",
        "carbs_per_100g": 15.0,
        "serving_size_g": 165,
        "serving_name": "كوب مقطّع",
        "image_url": "https://images.unsplash.com/photo-1553279768-865429fa0078?w=400&q=80",
        "notes": "حلو ولذيذ — راقب الكمية",
    },
    {
        "name": "تمر",
        "category": "فواكه",
        "carbs_per_100g": 75.0,
        "serving_size_g": 24,
        "serving_name": "3 حبات",
        "image_url": "https://images.unsplash.com/photo-1609171435614-e256d00a5d0b?w=400&q=80",
        "notes": "كارب مرتفع جداً — تناول بكميات صغيرة",
    },
    # ── خضروات ────────────────────────────────────────────────────────────────
    {
        "name": "بروكلي",
        "category": "خضروات",
        "carbs_per_100g": 6.6,
        "serving_size_g": 91,
        "serving_name": "كوب واحد",
        "image_url": "https://images.unsplash.com/photo-1584270354949-c26b0d5b4a0c?w=400&q=80",
        "notes": "خيار ممتاز — كربوهيدرات منخفضة جداً",
    },
    {
        "name": "سبانخ",
        "category": "خضروات",
        "carbs_per_100g": 3.6,
        "serving_size_g": 30,
        "serving_name": "كوب واحد",
        "image_url": "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&q=80",
        "notes": "تناوله بحرية — كارب منخفض جداً",
    },
    {
        "name": "جزر (نيء)",
        "category": "خضروات",
        "carbs_per_100g": 10.0,
        "serving_size_g": 61,
        "serving_name": "حبة متوسطة",
        "image_url": "https://images.unsplash.com/photo-1590868309235-ea34bed7bd7f?w=400&q=80",
        "notes": "الطهي يرفع الكارب قليلاً",
    },
    {
        "name": "بطاطا حلوة (مشوية)",
        "category": "خضروات",
        "carbs_per_100g": 20.7,
        "serving_size_g": 114,
        "serving_name": "حبة متوسطة",
        "image_url": "https://images.unsplash.com/photo-1596097635121-14b63b7a0c19?w=400&q=80",
        "notes": "أفضل من البطاطا العادية",
    },
    {
        "name": "بطاطا (مسلوقة)",
        "category": "خضروات",
        "carbs_per_100g": 17.0,
        "serving_size_g": 150,
        "serving_name": "حبة متوسطة",
        "image_url": "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400&q=80",
        "notes": "التبريد بعد الطهي يقلل الكارب قليلاً",
    },
    {
        "name": "طماطم",
        "category": "خضروات",
        "carbs_per_100g": 3.9,
        "serving_size_g": 123,
        "serving_name": "حبة متوسطة",
        "image_url": "https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=400&q=80",
        "notes": "كربوهيدرات منخفضة جداً",
    },
    {
        "name": "ذرة (مطبوخة)",
        "category": "خضروات",
        "carbs_per_100g": 21.0,
        "serving_size_g": 154,
        "serving_name": "كوب واحد",
        "image_url": "https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400&q=80",
        "notes": "تُحسب كنشوية لا كخضروات",
    },
    # ── حلويات ────────────────────────────────────────────────────────────────
    {
        "name": "كيكة عادية (شريحة)",
        "category": "حلويات",
        "carbs_per_100g": 52.0,
        "serving_size_g": 80,
        "serving_name": "شريحة واحدة",
        "image_url": "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&q=80",
        "notes": "عالية جداً في الكارب والسكر",
    },
    {
        "name": "شوكولاتة حليب",
        "category": "حلويات",
        "carbs_per_100g": 59.0,
        "serving_size_g": 40,
        "serving_name": "لوح صغير",
        "image_url": "https://images.unsplash.com/photo-1511381939415-e44015466834?w=400&q=80",
        "notes": "كارب ومرتفع — أحياناً نادرة فقط",
    },
    {
        "name": "آيس كريم (كرة)",
        "category": "حلويات",
        "carbs_per_100g": 24.0,
        "serving_size_g": 66,
        "serving_name": "كرة واحدة",
        "image_url": "https://images.unsplash.com/photo-1567206563114-c179706a56e9?w=400&q=80",
        "notes": "سكر عالٍ — تناول بكميات صغيرة",
    },
    {
        "name": "بسكويت (3 قطع)",
        "category": "حلويات",
        "carbs_per_100g": 70.0,
        "serving_size_g": 30,
        "serving_name": "3 قطع",
        "image_url": "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&q=80",
        "notes": "سكر ونشا عاليان",
    },
    {
        "name": "كنافة",
        "category": "حلويات",
        "carbs_per_100g": 44.0,
        "serving_size_g": 150,
        "serving_name": "حصة متوسطة",
        "image_url": "https://images.unsplash.com/photo-1609171435614-e256d00a5d0b?w=400&q=80",
        "notes": "حلوى شرقية — كارب مرتفع جداً",
    },
    {
        "name": "بقلاوة (3 قطع)",
        "category": "حلويات",
        "carbs_per_100g": 40.0,
        "serving_size_g": 60,
        "serving_name": "3 قطع",
        "image_url": "https://images.unsplash.com/photo-1599785209707-a456fc1337bb?w=400&q=80",
        "notes": "كارب مرتفع وسكر — اقتصر على القليل",
    },
    # ── مشروبات ───────────────────────────────────────────────────────────────
    {
        "name": "عصير برتقال طبيعي",
        "category": "مشروبات",
        "carbs_per_100g": 10.4,
        "serving_size_g": 240,
        "serving_name": "كوب واحد",
        "image_url": "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=400&q=80",
        "notes": "أسرع في رفع السكر من الفاكهة الكاملة",
    },
    {
        "name": "عصير تفاح معبأ",
        "category": "مشروبات",
        "carbs_per_100g": 11.7,
        "serving_size_g": 240,
        "serving_name": "كوب واحد",
        "image_url": "https://images.unsplash.com/photo-1576673442511-7e39b6545c87?w=400&q=80",
        "notes": "يفتقر للألياف — فضّل الفاكهة الكاملة",
    },
    {
        "name": "مشروب غازي (كوكاكولا)",
        "category": "مشروبات",
        "carbs_per_100g": 10.6,
        "serving_size_g": 355,
        "serving_name": "علبة واحدة",
        "image_url": "https://images.unsplash.com/photo-1534353436294-0dbd4bdac845?w=400&q=80",
        "notes": "سكر مرتفع جداً — تجنبه لمرضى السكري",
    },
    {
        "name": "حليب كامل الدسم",
        "category": "مشروبات",
        "carbs_per_100g": 4.8,
        "serving_size_g": 244,
        "serving_name": "كوب واحد",
        "image_url": "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&q=80",
        "notes": "متوسط — راقب إجمالي الكارب",
    },
    {
        "name": "قهوة بسكر (كوب)",
        "category": "مشروبات",
        "carbs_per_100g": 5.0,
        "serving_size_g": 240,
        "serving_name": "كوب واحد",
        "image_url": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&q=80",
        "notes": "السكر المضاف يرفع الكارب بشكل كبير",
    },
    {
        "name": "شاي بسكر",
        "category": "مشروبات",
        "carbs_per_100g": 8.0,
        "serving_size_g": 240,
        "serving_name": "كوب واحد",
        "image_url": "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&q=80",
        "notes": "السكر المضاف — فضّل الشاي بدون سكر",
    },
    # ── وجبات مطاعم ───────────────────────────────────────────────────────────
    {
        "name": "كبسة دجاج (طبق)",
        "category": "وجبات مطاعم",
        "carbs_per_100g": 22.0,
        "serving_size_g": 400,
        "serving_name": "طبق واحد",
        "image_url": "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=400&q=80",
        "notes": "معظم الكارب من الأرز",
    },
    {
        "name": "شاورما دجاج (ساندويش)",
        "category": "وجبات مطاعم",
        "carbs_per_100g": 25.0,
        "serving_size_g": 250,
        "serving_name": "ساندويش واحد",
        "image_url": "https://images.unsplash.com/photo-1561651188-d207bbec4ec3?w=400&q=80",
        "notes": "الخبز يشكّل معظم الكارب",
    },
    {
        "name": "فول مدمس (طبق)",
        "category": "وجبات مطاعم",
        "carbs_per_100g": 14.4,
        "serving_size_g": 200,
        "serving_name": "طبق متوسط",
        "image_url": "https://images.unsplash.com/photo-1547592180-85f173990554?w=400&q=80",
        "notes": "بروتين وألياف ممتازة",
    },
    {
        "name": "مجبوس لحم (طبق)",
        "category": "وجبات مطاعم",
        "carbs_per_100g": 20.0,
        "serving_size_g": 400,
        "serving_name": "طبق واحد",
        "image_url": "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=400&q=80",
        "notes": "الأرز يمثل الجزء الأكبر من الكارب",
    },
    # ── وجبات سريعة ───────────────────────────────────────────────────────────
    {
        "name": "برغر دجاج",
        "category": "وجبات سريعة",
        "carbs_per_100g": 27.0,
        "serving_size_g": 200,
        "serving_name": "برغر واحد",
        "image_url": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&q=80",
        "notes": "الخبز والصلصة يرفعان الكارب",
    },
    {
        "name": "بطاطس مقلية (وسط)",
        "category": "وجبات سريعة",
        "carbs_per_100g": 41.0,
        "serving_size_g": 117,
        "serving_name": "حصة وسط",
        "image_url": "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&q=80",
        "notes": "كارب مرتفع جداً — قلل الكمية",
    },
    {
        "name": "هوت دوج",
        "category": "وجبات سريعة",
        "carbs_per_100g": 22.0,
        "serving_size_g": 98,
        "serving_name": "واحد",
        "image_url": "https://images.unsplash.com/photo-1612392166886-ee8475b03af2?w=400&q=80",
        "notes": "الخبز يحمل الجزء الأكبر من الكارب",
    },
    {
        "name": "رول سمك",
        "category": "وجبات سريعة",
        "carbs_per_100g": 30.0,
        "serving_size_g": 180,
        "serving_name": "رول واحد",
        "image_url": "https://images.unsplash.com/photo-1519984388953-d2406bc725e1?w=400&q=80",
        "notes": "الخبز يشكّل معظم الكارب",
    },
    # ── منتجات بملصق غذائي ────────────────────────────────────────────────────
    {
        "name": "حبوب إفطار (كورن فليكس)",
        "category": "منتجات بملصق غذائي",
        "carbs_per_100g": 84.0,
        "serving_size_g": 30,
        "serving_name": "¾ كوب",
        "image_url": "https://images.unsplash.com/photo-1521483451569-e33803c0330c?w=400&q=80",
        "notes": "اقرأ الملصق — السكر المضاف قد يكون عالياً",
    },
    {
        "name": "مربى فواكه (ملعقة)",
        "category": "منتجات بملصق غذائي",
        "carbs_per_100g": 65.0,
        "serving_size_g": 20,
        "serving_name": "ملعقة كبيرة",
        "image_url": "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&q=80",
        "notes": "سكر مضاف مرتفع — استخدم بمقادير صغيرة",
    },
    {
        "name": "صوص طماطم (ملعقة)",
        "category": "منتجات بملصق غذائي",
        "carbs_per_100g": 26.0,
        "serving_size_g": 17,
        "serving_name": "ملعقة كبيرة",
        "image_url": "https://images.unsplash.com/photo-1571167530149-c1105da4c2c3?w=400&q=80",
        "notes": "سكر مضاف — افحص الملصق دائماً",
    },
    {
        "name": "جبن مشكل (شريحة)",
        "category": "منتجات بملصق غذائي",
        "carbs_per_100g": 3.5,
        "serving_size_g": 28,
        "serving_name": "شريحة واحدة",
        "image_url": "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400&q=80",
        "notes": "كارب منخفض — مصدر جيد للبروتين",
    },
    # ── ألبان ─────────────────────────────────────────────────────────────────
    {
        "name": "زبادي سادة (قليل الدسم)",
        "category": "ألبان",
        "carbs_per_100g": 7.0,
        "serving_size_g": 245,
        "serving_name": "كوب واحد",
        "image_url": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&q=80",
        "notes": "البروتين يبطئ امتصاص السكر",
    },
    {
        "name": "زبادي يوناني (سادة)",
        "category": "ألبان",
        "carbs_per_100g": 3.6,
        "serving_size_g": 245,
        "serving_name": "كوب واحد",
        "image_url": "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&q=80",
        "notes": "بروتين عالٍ وكارب منخفض جداً",
    },
    {
        "name": "جبن قريش",
        "category": "ألبان",
        "carbs_per_100g": 3.4,
        "serving_size_g": 113,
        "serving_name": "نصف كوب",
        "image_url": "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400&q=80",
        "notes": "ممتاز لمرضى السكري — كارب منخفض",
    },
    # ── بروتينات ──────────────────────────────────────────────────────────────
    {
        "name": "صدر دجاج (مشوي)",
        "category": "بروتينات",
        "carbs_per_100g": 0.0,
        "serving_size_g": 85,
        "serving_name": "85 غرام",
        "image_url": "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=400&q=80",
        "notes": "صفر كارب — ممتاز لضبط السكر",
    },
    {
        "name": "سمك سلمون (مشوي)",
        "category": "بروتينات",
        "carbs_per_100g": 0.0,
        "serving_size_g": 85,
        "serving_name": "قطعة واحدة",
        "image_url": "https://images.unsplash.com/photo-1519984388953-d2406bc725e1?w=400&q=80",
        "notes": "صفر كارب وأوميغا-3 ممتازة",
    },
    {
        "name": "بيض (مسلوق)",
        "category": "بروتينات",
        "carbs_per_100g": 0.6,
        "serving_size_g": 50,
        "serving_name": "بيضة واحدة",
        "image_url": "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400&q=80",
        "notes": "كارب شبه معدوم — ممتاز للإفطار",
    },
    {
        "name": "عدس (مطبوخ)",
        "category": "بروتينات",
        "carbs_per_100g": 20.0,
        "serving_size_g": 198,
        "serving_name": "كوب واحد",
        "image_url": "https://images.unsplash.com/photo-1604135945956-a30cc5dcacf2?w=400&q=80",
        "notes": "بروتين وألياف ممتازة — كارب متوسط",
    },
    {
        "name": "حمص (مطبوخ)",
        "category": "بروتينات",
        "carbs_per_100g": 27.4,
        "serving_size_g": 164,
        "serving_name": "كوب واحد",
        "image_url": "https://images.unsplash.com/photo-1515543904379-3d757afe72e4?w=400&q=80",
        "notes": "الألياف ترفع الشبع وتبطئ الامتصاص",
    },
    # ── سناكات ────────────────────────────────────────────────────────────────
    {
        "name": "لوز (حفنة)",
        "category": "سناكات",
        "carbs_per_100g": 22.0,
        "serving_size_g": 28,
        "serving_name": "~23 حبة",
        "image_url": "https://images.unsplash.com/photo-1574570069985-0e9908c91ac7?w=400&q=80",
        "notes": "دهون صحية — كارب صافٍ منخفض",
    },
    {
        "name": "فول سوداني (حفنة)",
        "category": "سناكات",
        "carbs_per_100g": 16.0,
        "serving_size_g": 28,
        "serving_name": "~28 حبة",
        "image_url": "https://images.unsplash.com/photo-1558642891-54be180ea339?w=400&q=80",
        "notes": "بروتين ودهون تبطئ ارتفاع السكر",
    },
    {
        "name": "رقائق البطاطس (شيبس)",
        "category": "سناكات",
        "carbs_per_100g": 53.0,
        "serving_size_g": 28,
        "serving_name": "حفنة صغيرة",
        "image_url": "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400&q=80",
        "notes": "كارب مرتفع جداً — تجنبه أو قلله",
    },
    {
        "name": "كراكر قمح كامل (5 قطع)",
        "category": "سناكات",
        "carbs_per_100g": 67.0,
        "serving_size_g": 15,
        "serving_name": "5 قطع",
        "image_url": "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&q=80",
        "notes": "أفضل من الشيبس — مع جبن لتقليل ارتفاع السكر",
    },
    {
        "name": "زبادي بالفواكه (معبأ)",
        "category": "سناكات",
        "carbs_per_100g": 17.0,
        "serving_size_g": 170,
        "serving_name": "عبوة واحدة",
        "image_url": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&q=80",
        "notes": "افحص الملصق — السكر المضاف قد يكون عالياً",
    },
    {
        "name": "حبوب البوشار (بدون زبدة)",
        "category": "سناكات",
        "carbs_per_100g": 78.0,
        "serving_size_g": 28,
        "serving_name": "3 أكواب",
        "image_url": "https://images.unsplash.com/photo-1585647347483-22b66260dfff?w=400&q=80",
        "notes": "كارب مرتفع لكنه سناك خفيف نسبياً",
    },
]

CATEGORIES = [
    "أرز وحبوب",
    "خبز ومعجنات",
    "فواكه",
    "خضروات",
    "حلويات",
    "مشروبات",
    "وجبات مطاعم",
    "منتجات بملصق غذائي",
    "وجبات سريعة",
    "ألبان",
    "بروتينات",
    "سناكات",
]
